[package]
name = "rust-hwi"
version = "0.1.0"
authors = ["Daniela Brozzoni <danielabrozzoni@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = { version = "0.23", features = ["use-serde"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = { version = "^1.0" }
strum_macros = "0.18.0"
base64 = "^0.11"

[dev-dependencies]
serial_test = "0.4.0"
